<?php
/**
 * Übersetzungswörterbuch fürs UI (DE/EN/FR). Ein Key pro Textbaustein, pro
 * Sprache ein Wert. Platzhalter folgen sprintf-Syntax (%s, %d) und werden
 * von t() per vsprintf() eingesetzt (siehe i18n.php).
 *
 * Neue Sprache hinzufügen: einfach einen weiteren Top-Level-Key mit denselben
 * Keys ergänzen und in i18n.php's I18N_SUPPORTED eintragen. Fehlt ein Key in
 * einer Sprache, fällt t() automatisch auf Englisch zurück.
 */

return [

    'de' => [
        // Navigation / Header
        'nav.theme_toggle_aria' => 'Theme wechseln',
        'nav.lang_toggle_aria'  => 'Sprache wechseln',

        // DID-Suche (index.php)
        'search.did_placeholder' => 'DID durchsuchen (über alle APIs)…',
        'search.hint'             => 'Durchsucht alle Trust Statements der gewählten Umgebung nach dem eingegebenen Begriff (z.B. eine DID).',
        'search.entity_label'     => 'Entität laut idTS',
        'search.hit_singular'     => 'Treffer',
        'search.hit_plural'       => 'Treffer',
        'search.hit_n'            => 'Treffer %d',

        // Gemeinsame Begriffe
        'common.search_button' => 'Suchen',
        'common.error'         => 'Fehler',
        'common.loading'       => 'Lädt…',
        'common.status'        => 'Status',
        'common.validity'      => 'Validity',

        // Explorer (index.php)
        'explorer.select_prompt' => 'Bitte oben eine Umgebung und eine API auswählen.',
        'explorer.fetch_error'   => 'Fehler beim Abrufen/Dekodieren: %s',
        'toolbar.search_placeholder' => 'Suchen…',

        // Gültigkeits-/Statuspanel einer Trust-List
        'listmeta.hint'               => 'Gültigkeit dieser Trust-List (gilt für die gesamte Liste)',
        'listmeta.valid_from'         => 'Gültig ab (nbf)',
        'listmeta.valid_until'        => 'Gültig bis (exp)',
        'listmeta.created_at'         => 'Erstellt am (iat)',
        'listmeta.status_unavailable' => 'Status nicht abrufbar (%s)',

        // Tabelle & Pagination
        'table.no_entries'    => 'Keine Einträge gefunden.',
        'pagination.per_page' => 'Pro Seite',
        'pagination.first'    => 'Erste Seite',
        'pagination.prev'     => 'Vorherige Seite',
        'pagination.next'     => 'Nächste Seite',
        'pagination.last'     => 'Letzte Seite',
        'pagination.page'     => 'Seite',
        'pagination.of'       => 'von',
        'meta.entries'        => '%d Einträge',
        'meta.filtered_from'  => '(gefiltert aus %d)',
        'meta.showing'        => 'zeige %d–%d',

        // History-Seite
        'history.range_label'      => 'Zeitraum',
        'history.from'             => 'Von',
        'history.to'               => 'Bis',
        'history.scale_label'      => 'Skala',
        'history.scale_log'        => 'Logarithmisch',
        'history.scale_linear'     => 'Linear',
        'history.select_label'     => 'Auswählen:',
        'history.all_x'            => 'Alle %s',
        'history.deselect_all'     => 'Alle abwählen',
        'history.apply'            => 'Anzeigen',
        'history.db_error'         => 'Fehler beim Zugriff auf die History-Datenbank: %s',
        'history.select_prompt'    => 'Bitte oben mindestens eine Kombination aus Umgebung und API auswählen und auf "Anzeigen" klicken.',
        'history.meta_range'       => 'Zeitraum: %s',
        'history.meta_curves'      => '%d Kurve(n)',
        'history.meta_points'      => '%d Datenpunkte insgesamt',
        'history.collector_errors' => '%d fehlgeschlagene(r) Collector-Lauf/Läufe im gewählten Zeitraum (im Chart als Lücke sichtbar).',
        'chart.axis_time'          => 'Zeit',
        'chart.axis_count'         => 'Anzahl Trust Statements',

        // Spaltentitel (config.php) — nur die tatsächlich deutschen; rein
        // englische/technische Spaltentitel sind in beiden Sprachen identisch
        // und direkt in config.php hinterlegt (kein Key nötig).
        'col.flagged_at' => 'Geflaggt am',
        'col.reason_de'  => 'Grund (DE)',
        'col.reason_en'  => 'Grund (EN)',
        'col.reason_fr'  => 'Grund (FR)',
        'col.reason_it'  => 'Grund (IT)',
        'col.reason_rm'  => 'Grund (RM)',
        'col.vct_value'  => 'VCT-Wert',

        // Zeitraum-Presets (config.php 'history.range_options')
        'range.7d'     => 'Letzte 7 Tage',
        'range.30d'    => 'Letzte 30 Tage',
        'range.90d'    => 'Letzte 90 Tage',
        'range.1y'     => 'Letztes Jahr',
        'range.all'    => 'Alle Daten',
        'range.custom' => 'Benutzerdefiniert',

        // Statuswerte / Detailansicht / Fehlermeldungen (functions.php)
        'issuers.none_found'           => 'Keine Issuer für diesen VCT gefunden.',
        'validity.not_yet_valid'       => 'noch nicht gültig',
        'validity.expired'             => 'abgelaufen',
        'validity.valid'               => 'gültig',
        'status.unavailable'           => 'nicht abrufbar',
        'cell.empty'                   => '(leer)',
        'detail.jwt_header'            => 'JWT-Header',
        'detail.payload_full'          => 'Payload (vollständig)',
        'error.invalid_jwt'            => 'Ungültiges JWT-Format.',
        'error.curl'                   => 'cURL-Fehler (%d): %s',
        'error.http_status'            => 'Unerwarteter HTTP-Status: %d für %s',
        'error.empty_response'         => 'Leere Antwort von der API.',
        'error.status_list_missing'    => 'status_list-Feld fehlt in der Antwort',
        'error.status_list_decompress' => 'Statusliste konnte nicht entpackt werden',
        'error.status_list_index_oob'  => 'Index ausserhalb der Statusliste',
        'error.history_dir'            => 'Konnte Verzeichnis für History-DB nicht anlegen: %s',
        'error.unknown_api_mode'       => 'Unbekannter API-Modus: %s',

        // Base Registry (did.jsonl-Abfrage pro DID)
        'base.title'               => 'Base Registry',
        'base.trust_registry'      => 'Trust Registry',
        'base.other_apis'          => 'Weitere APIs',
        'base.open_in_explorer'    => 'Im Explorer öffnen',
        'base.show_statement'      => 'Vollständiges Statement anzeigen',
        'base.no_did'              => 'Keine DID zum Nachschlagen. Für eine Abfrage im Base Registry eine vollständige DID eingeben.',
        'base.tab.statement'       => 'Trust Statement',
        'base.status.active'       => 'Aktiv',
        'base.status.found'        => 'Gefunden',
        'base.status.deactivated'  => 'Deaktiviert',
        'base.status.not_found'    => 'Nicht gefunden',
        'base.status.external'     => 'Externe DID',
        'base.status.unavailable'  => 'Nicht verfügbar',
        'base.status.loading'      => 'Lädt …',
        'base.versions_one'        => '%d Version',
        'base.versions_many'       => '%d Versionen',
        'base.hint.external'       => 'Diese DID wird nicht vom Base Registry dieser Umgebung gehostet.',
        'base.hint.not_found'      => 'Das Base Registry hat keinen Eintrag zu dieser DID (HTTP 404).',
        'base.retry'               => 'Erneut versuchen',
        'base.field.method'        => 'Methode',
        'base.field.versions'      => 'Versionen',
        'base.field.created'       => 'Erstellt',
        'base.field.last_update'   => 'Letzte Änderung',
        'base.field.keys'          => 'Schlüssel',
        'base.field.uuid'          => 'Lookup-UUID',
        'base.view_log'            => 'DID-Log anzeigen',
        'base.open_jsonl'          => 'did.jsonl öffnen',
        'base.open_jsonl_tab'      => 'did.jsonl in neuem Tab öffnen',
        'base.dialog_title'        => 'DID-Log',
        'base.close'               => 'Schliessen',
        'base.view_parsed'         => 'Aufbereitet',
        'base.view_raw'            => 'Rohantwort',
        'base.copy'                => 'Kopieren',
        'base.copied'              => 'Kopiert',
        'base.request_line'        => 'GET %s · HTTP %d · %d Log-Zeile(n)',
        'base.section.versions'    => 'Versionshistorie',
        'base.section.keys'        => 'Schlüssel im aktuellen DID-Dokument',
        'base.section.raw'         => 'Rohes DID-Log (did.jsonl)',
        'base.col.timestamp'       => 'Zeitstempel',
        'base.col.update_key'      => 'Update-Key',
        'base.col.change'          => 'Änderung',
        'base.col.purpose'         => 'Verwendung',
        'base.col.type'            => 'Typ',
        'base.col.curve'           => 'Kurve',
        'base.change.created'      => 'Erstellt',
        'base.change.updated'      => 'Aktualisiert',
        'base.change.deactivated'  => 'Deaktiviert',
        'base.keys_stale_note'     => 'Der neueste Log-Eintrag ist ein Patch; die Schlüssel stammen aus Version %d.',
        'base.keys_none'           => 'keine',
        'base.error.http'          => 'Das Base Registry antwortete mit HTTP %d.',
        'base.error.invalid_log'   => 'Ungültiges DID-Log-Format.',
    ],

    'en' => [
        'nav.theme_toggle_aria' => 'Switch theme',
        'nav.lang_toggle_aria'  => 'Switch language',

        'search.did_placeholder' => 'Search DID (across all APIs)…',
        'search.hint'             => 'Searches all Trust Statements in the selected environment for the entered term (e.g. a DID).',
        'search.entity_label'     => 'Entity per idTS',
        'search.hit_singular'     => 'hit',
        'search.hit_plural'       => 'hits',
        'search.hit_n'            => 'Match %d',

        'common.search_button' => 'Search',
        'common.error'         => 'Error',
        'common.loading'       => 'Loading…',
        'common.status'        => 'Status',
        'common.validity'      => 'Validity',

        'explorer.select_prompt' => 'Please select an environment and an API above.',
        'explorer.fetch_error'   => 'Error fetching/decoding: %s',
        'toolbar.search_placeholder' => 'Search…',

        'listmeta.hint'               => 'Validity of this trust list (applies to the entire list)',
        'listmeta.valid_from'         => 'Valid from (nbf)',
        'listmeta.valid_until'        => 'Valid until (exp)',
        'listmeta.created_at'         => 'Created at (iat)',
        'listmeta.status_unavailable' => 'Status unavailable (%s)',

        'table.no_entries'    => 'No entries found.',
        'pagination.per_page' => 'Per page',
        'pagination.first'    => 'First page',
        'pagination.prev'     => 'Previous page',
        'pagination.next'     => 'Next page',
        'pagination.last'     => 'Last page',
        'pagination.page'     => 'Page',
        'pagination.of'       => 'of',
        'meta.entries'        => '%d entries',
        'meta.filtered_from'  => '(filtered from %d)',
        'meta.showing'        => 'showing %d–%d',

        'history.range_label'      => 'Time range',
        'history.from'             => 'From',
        'history.to'               => 'To',
        'history.scale_label'      => 'Scale',
        'history.scale_log'        => 'Logarithmic',
        'history.scale_linear'     => 'Linear',
        'history.select_label'     => 'Select:',
        'history.all_x'            => 'All %s',
        'history.deselect_all'     => 'Deselect all',
        'history.apply'            => 'Show',
        'history.db_error'         => 'Error accessing the History database: %s',
        'history.select_prompt'    => 'Please select at least one environment/API combination above and click "Show".',
        'history.meta_range'       => 'Time range: %s',
        'history.meta_curves'      => '%d curve(s)',
        'history.meta_points'      => '%d data points total',
        'history.collector_errors' => '%d failed collector run(s) in the selected time range (shown as a gap in the chart).',
        'chart.axis_time'          => 'Time',
        'chart.axis_count'         => 'Number of Trust Statements',

        'col.flagged_at' => 'Flagged At',
        'col.reason_de'  => 'Reason (DE)',
        'col.reason_en'  => 'Reason (EN)',
        'col.reason_fr'  => 'Reason (FR)',
        'col.reason_it'  => 'Reason (IT)',
        'col.reason_rm'  => 'Reason (RM)',
        'col.vct_value'  => 'VCT Value',

        'range.7d'     => 'Last 7 days',
        'range.30d'    => 'Last 30 days',
        'range.90d'    => 'Last 90 days',
        'range.1y'     => 'Last year',
        'range.all'    => 'All data',
        'range.custom' => 'Custom',

        'issuers.none_found'           => 'No issuers found for this VCT.',
        'validity.not_yet_valid'       => 'not yet valid',
        'validity.expired'             => 'expired',
        'validity.valid'               => 'valid',
        'status.unavailable'           => 'not available',
        'cell.empty'                   => '(empty)',
        'detail.jwt_header'            => 'JWT Header',
        'detail.payload_full'          => 'Payload (complete)',
        'error.invalid_jwt'            => 'Invalid JWT format.',
        'error.curl'                   => 'cURL error (%d): %s',
        'error.http_status'            => 'Unexpected HTTP status: %d for %s',
        'error.empty_response'         => 'Empty response from the API.',
        'error.status_list_missing'    => 'status_list field missing in the response',
        'error.status_list_decompress' => 'Status list could not be decompressed',
        'error.status_list_index_oob'  => 'Index outside the status list',
        'error.history_dir'            => 'Could not create directory for the History DB: %s',
        'error.unknown_api_mode'       => 'Unknown API mode: %s',

        // Base Registry (did.jsonl lookup per DID)
        'base.title'               => 'Base Registry',
        'base.trust_registry'      => 'Trust Registry',
        'base.other_apis'          => 'Other APIs',
        'base.open_in_explorer'    => 'Open in Explorer',
        'base.show_statement'      => 'Show full statement',
        'base.no_did'              => 'No DID to look up. Enter a full DID to query the Base Registry.',
        'base.tab.statement'       => 'Trust Statement',
        'base.status.active'       => 'Active',
        'base.status.found'        => 'Found',
        'base.status.deactivated'  => 'Deactivated',
        'base.status.not_found'    => 'Not found',
        'base.status.external'     => 'External DID',
        'base.status.unavailable'  => 'Unavailable',
        'base.status.loading'      => 'Loading…',
        'base.versions_one'        => '%d version',
        'base.versions_many'       => '%d versions',
        'base.hint.external'       => 'This DID is not hosted by the Base Registry of this environment.',
        'base.hint.not_found'      => 'The Base Registry has no entry for this DID (HTTP 404).',
        'base.retry'               => 'Retry',
        'base.field.method'        => 'Method',
        'base.field.versions'      => 'Versions',
        'base.field.created'       => 'Created',
        'base.field.last_update'   => 'Last update',
        'base.field.keys'          => 'Keys',
        'base.field.uuid'          => 'Lookup UUID',
        'base.view_log'            => 'View DID log',
        'base.open_jsonl'          => 'Open did.jsonl',
        'base.open_jsonl_tab'      => 'Open did.jsonl in new tab',
        'base.dialog_title'        => 'DID log',
        'base.close'               => 'Close',
        'base.view_parsed'         => 'Parsed',
        'base.view_raw'            => 'Raw response',
        'base.copy'                => 'Copy',
        'base.copied'              => 'Copied',
        'base.request_line'        => 'GET %s · HTTP %d · %d log line(s)',
        'base.section.versions'    => 'Version history',
        'base.section.keys'        => 'Keys in the current DID document',
        'base.section.raw'         => 'Raw DID log (did.jsonl)',
        'base.col.timestamp'       => 'Timestamp',
        'base.col.update_key'      => 'Update key',
        'base.col.change'          => 'Change',
        'base.col.purpose'         => 'Purpose',
        'base.col.type'            => 'Type',
        'base.col.curve'           => 'Curve',
        'base.change.created'      => 'Created',
        'base.change.updated'      => 'Updated',
        'base.change.deactivated'  => 'Deactivated',
        'base.keys_stale_note'     => 'The latest log entry is a patch; keys are shown from version %d.',
        'base.keys_none'           => 'none',
        'base.error.http'          => 'The Base Registry answered with HTTP %d.',
        'base.error.invalid_log'   => 'Invalid DID log format.',
    ],

    'fr' => [
        'nav.theme_toggle_aria' => 'Changer de thème',
        'nav.lang_toggle_aria'  => 'Changer de langue',

        'search.did_placeholder' => 'Rechercher un DID (dans toutes les API)…',
        'search.hint'             => 'Recherche le terme saisi (p. ex. un DID) dans tous les Trust Statements de l\'environnement sélectionné.',
        'search.entity_label'     => 'Entité selon idTS',
        'search.hit_singular'     => 'résultat',
        'search.hit_plural'       => 'résultats',
        'search.hit_n'            => 'Résultat %d',

        'common.search_button' => 'Rechercher',
        'common.error'         => 'Erreur',
        'common.loading'       => 'Chargement…',
        'common.status'        => 'Statut',
        'common.validity'      => 'Validité',

        'explorer.select_prompt' => 'Veuillez sélectionner un environnement et une API ci-dessus.',
        'explorer.fetch_error'   => 'Erreur lors de la récupération/du décodage : %s',
        'toolbar.search_placeholder' => 'Rechercher…',

        'listmeta.hint'               => 'Validité de cette trust list (s\'applique à la liste entière)',
        'listmeta.valid_from'         => 'Valide à partir de (nbf)',
        'listmeta.valid_until'        => 'Valide jusqu\'à (exp)',
        'listmeta.created_at'         => 'Créé le (iat)',
        'listmeta.status_unavailable' => 'Statut indisponible (%s)',

        'table.no_entries'    => 'Aucune entrée trouvée.',
        'pagination.per_page' => 'Par page',
        'pagination.first'    => 'Première page',
        'pagination.prev'     => 'Page précédente',
        'pagination.next'     => 'Page suivante',
        'pagination.last'     => 'Dernière page',
        'pagination.page'     => 'Page',
        'pagination.of'       => 'sur',
        'meta.entries'        => '%d entrées',
        'meta.filtered_from'  => '(filtré depuis %d)',
        'meta.showing'        => 'affichage %d–%d',

        'history.range_label'      => 'Période',
        'history.from'             => 'De',
        'history.to'               => 'À',
        'history.scale_label'      => 'Échelle',
        'history.scale_log'        => 'Logarithmique',
        'history.scale_linear'     => 'Linéaire',
        'history.select_label'     => 'Sélectionner :',
        'history.all_x'            => 'Tous : %s',
        'history.deselect_all'     => 'Tout désélectionner',
        'history.apply'            => 'Afficher',
        'history.db_error'         => 'Erreur d\'accès à la base de données History : %s',
        'history.select_prompt'    => 'Veuillez sélectionner au moins une combinaison environnement/API ci-dessus et cliquer sur « Afficher ».',
        'history.meta_range'       => 'Période : %s',
        'history.meta_curves'      => '%d courbe(s)',
        'history.meta_points'      => '%d points de données au total',
        'history.collector_errors' => '%d exécution(s) du collecteur ayant échoué dans la période sélectionnée (visible comme un espace vide dans le graphique).',
        'chart.axis_time'          => 'Temps',
        'chart.axis_count'         => 'Nombre de Trust Statements',

        'col.flagged_at' => 'Signalé le',
        'col.reason_de'  => 'Motif (DE)',
        'col.reason_en'  => 'Motif (EN)',
        'col.reason_fr'  => 'Motif (FR)',
        'col.reason_it'  => 'Motif (IT)',
        'col.reason_rm'  => 'Motif (RM)',
        'col.vct_value'  => 'Valeur VCT',

        'range.7d'     => '7 derniers jours',
        'range.30d'    => '30 derniers jours',
        'range.90d'    => '90 derniers jours',
        'range.1y'     => 'Dernière année',
        'range.all'    => 'Toutes les données',
        'range.custom' => 'Personnalisé',

        'issuers.none_found'           => 'Aucun émetteur trouvé pour ce VCT.',
        'validity.not_yet_valid'       => 'pas encore valide',
        'validity.expired'             => 'expiré',
        'validity.valid'               => 'valide',
        'status.unavailable'           => 'indisponible',
        'cell.empty'                   => '(vide)',
        'detail.jwt_header'            => 'En-tête JWT',
        'detail.payload_full'          => 'Payload (complet)',
        'error.invalid_jwt'            => 'Format JWT invalide.',
        'error.curl'                   => 'Erreur cURL (%d) : %s',
        'error.http_status'            => 'Statut HTTP inattendu : %d pour %s',
        'error.empty_response'         => 'Réponse vide de l\'API.',
        'error.status_list_missing'    => 'Champ status_list manquant dans la réponse',
        'error.status_list_decompress' => 'Impossible de décompresser la liste de statuts',
        'error.status_list_index_oob'  => 'Index hors de la liste de statuts',
        'error.history_dir'            => 'Impossible de créer le répertoire pour la base History : %s',
        'error.unknown_api_mode'       => 'Mode API inconnu : %s',

        // Base Registry (consultation du did.jsonl par DID)
        'base.title'               => 'Base Registry',
        'base.trust_registry'      => 'Trust Registry',
        'base.other_apis'          => 'Autres API',
        'base.open_in_explorer'    => 'Ouvrir dans l\'Explorer',
        'base.show_statement'      => 'Afficher la déclaration complète',
        'base.no_did'              => 'Aucun DID à consulter. Saisissez un DID complet pour interroger le Base Registry.',
        'base.tab.statement'       => 'Trust Statement',
        'base.status.active'       => 'Actif',
        'base.status.found'        => 'Trouvé',
        'base.status.deactivated'  => 'Désactivé',
        'base.status.not_found'    => 'Introuvable',
        'base.status.external'     => 'DID externe',
        'base.status.unavailable'  => 'Indisponible',
        'base.status.loading'      => 'Chargement…',
        'base.versions_one'        => '%d version',
        'base.versions_many'       => '%d versions',
        'base.hint.external'       => 'Ce DID n\'est pas hébergé par le Base Registry de cet environnement.',
        'base.hint.not_found'      => 'Le Base Registry n\'a aucune entrée pour ce DID (HTTP 404).',
        'base.retry'               => 'Réessayer',
        'base.field.method'        => 'Méthode',
        'base.field.versions'      => 'Versions',
        'base.field.created'       => 'Créé le',
        'base.field.last_update'   => 'Dernière modification',
        'base.field.keys'          => 'Clés',
        'base.field.uuid'          => 'UUID de recherche',
        'base.view_log'            => 'Afficher le journal DID',
        'base.open_jsonl'          => 'Ouvrir did.jsonl',
        'base.open_jsonl_tab'      => 'Ouvrir did.jsonl dans un nouvel onglet',
        'base.dialog_title'        => 'Journal DID',
        'base.close'               => 'Fermer',
        'base.view_parsed'         => 'Analysé',
        'base.view_raw'            => 'Réponse brute',
        'base.copy'                => 'Copier',
        'base.copied'              => 'Copié',
        'base.request_line'        => 'GET %s · HTTP %d · %d ligne(s) de journal',
        'base.section.versions'    => 'Historique des versions',
        'base.section.keys'        => 'Clés du document DID actuel',
        'base.section.raw'         => 'Journal DID brut (did.jsonl)',
        'base.col.timestamp'       => 'Horodatage',
        'base.col.update_key'      => 'Clé de mise à jour',
        'base.col.change'          => 'Modification',
        'base.col.purpose'         => 'Usage',
        'base.col.type'            => 'Type',
        'base.col.curve'           => 'Courbe',
        'base.change.created'      => 'Créé',
        'base.change.updated'      => 'Mis à jour',
        'base.change.deactivated'  => 'Désactivé',
        'base.keys_stale_note'     => 'La dernière entrée du journal est un patch ; les clés proviennent de la version %d.',
        'base.keys_none'           => 'aucune',
        'base.error.http'          => 'Le Base Registry a répondu avec HTTP %d.',
        'base.error.invalid_log'   => 'Format de journal DID invalide.',
    ],

];
